(function(){
  var boot=window.SCPS_DEPLOY||{};var current=null;var pollTimer=null;
  function el(id){return document.getElementById(id)}
  function jsonFetch(url,opts){return fetch(url,opts).then(function(r){return r.text().then(function(body){var j;try{j=body?JSON.parse(body):{}}catch(_e){throw new Error('Server returned a non-JSON response (HTTP '+r.status+'). Check the Saltcorn server log.')}if(!r.ok||j.ok===false)throw new Error(j.error||('HTTP '+r.status));return j})})}
  function post(url,body){return jsonFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
  function rail(name,state){var node=document.querySelector('[data-rail="'+name+'"]');if(node){node.classList.remove('active','done','failed');if(state)node.classList.add(state)}}
  function target(op){if(op.table&&op.field)return op.table+'.'+op.field;return op.table||op.field||op.view||op.page||op.trigger||op.role||op.plugin||op.setting||op.menu||op.from||''}
  function stat(label,value,kind){var d=document.createElement('div');d.className='scps-stat '+(kind||'');var strong=document.createElement('strong');strong.textContent=String(value||0);d.appendChild(strong);d.appendChild(document.createTextNode(label));return d}
  function alertBox(kind,text){var d=document.createElement('div');d.className='alert alert-'+kind;d.textContent=text;return d}
  function showPreview(j){
    current=j;rail('source','done');rail('preflight','done');rail('plan','active');el('deploy-source-panel').classList.add('d-none');el('deploy-plan-panel').classList.remove('d-none');
    var p=j.prepared,s=p.summary,alerts=el('deploy-alerts');alerts.textContent='';
    (p.plan.blocked||[]).forEach(function(x){alerts.appendChild(alertBox('danger',x.reason||JSON.stringify(x)))});(p.plan.warnings||[]).forEach(function(x){alerts.appendChild(alertBox('warning',(x.message||x.type||'Warning')+' — '+target(x)))});
    var stats=el('deploy-stats');stats.textContent='';stats.appendChild(stat('Safe',s.safe));stats.appendChild(stat('Destructive',s.destructive,'danger'));stats.appendChild(stat('Warnings',s.warnings,'warn'));stats.appendChild(stat('Blockers',s.blockers,s.blockers?'danger':''));
    var ops=el('deploy-operations');ops.textContent='';(p.plan.operations||[]).forEach(function(op){var row=document.createElement('div');row.className='scps-op';var action=document.createElement('code');action.textContent=op.action||'operation';var dest=document.createElement('span');dest.textContent=target(op);var badge=document.createElement('span');badge.className='badge '+(op.safe===false?'bg-danger':'bg-success');badge.textContent=op.safe===false?'destructive':'safe';row.append(action,dest,badge);ops.appendChild(row)});if(!(p.plan.operations||[]).length){ops.appendChild(alertBox('success','No changes to apply.'))}
    el('deploy-commit').textContent=j.source.commit.slice(0,12);el('deploy-digests').textContent='desired '+p.desired_digest+'\nactual  '+p.actual_digest+'\nplan    '+p.plan_digest;
    if(s.destructive){el('deploy-destructive-confirm').classList.remove('d-none');el('deploy-typed-env').addEventListener('input',updateConfirm)}
    updateConfirm();
  }
  function updateConfirm(){if(!current)return;var s=current.prepared.summary;var typed=!s.destructive||el('deploy-typed-env').value===boot.environment;el('btn-deploy-confirm').disabled=Boolean(s.blockers||!s.count||!typed)}
  el('btn-deploy-preview').addEventListener('click',function(){var b=this;b.disabled=true;b.innerHTML='<i class="fas fa-spinner fa-spin me-1"></i>Preparing…';post('/project-sync/api/projects/'+encodeURIComponent(boot.projectId)+'/deploy/preview',{environment:boot.environment,source_ref:el('deploy-source-ref').value,refresh_source:el('deploy-fetch-source').checked,backup_requested:el('deploy-backup').checked}).then(showPreview).catch(function(e){alert(e.message)}).finally(function(){b.disabled=false;b.textContent='Generate deployment plan'})});
  el('btn-deploy-environment').addEventListener('click',function(){var env=el('deploy-environment').value.trim();if(env)location.href='/project-sync/projects/'+encodeURIComponent(boot.projectId)+'/deploy?environment='+encodeURIComponent(env)});
  el('btn-deploy-confirm').addEventListener('click',function(){var b=this;b.disabled=true;post('/project-sync/api/deployment-requests/confirm',{request_id:current.request.request_id,plan_digest:current.prepared.plan_digest,typed_environment:el('deploy-typed-env').value}).then(function(){el('deploy-progress-panel').classList.remove('d-none');el('deploy-plan-panel').classList.add('d-none');rail('plan','done');rail('backup','active');poll()}).catch(function(e){b.disabled=false;alert(e.message)})});
  el('btn-deploy-cancel').addEventListener('click',function(){if(!current){location.reload();return}post('/project-sync/api/deployment-requests/cancel',{request_id:current.request.request_id}).finally(function(){location.reload()})});
  function terminal(status){return ['applied','drifted','backup_failed','apply_failed','refresh_failed','verify_failed','record_failed','stale','expired','cancelled'].includes(status)}
  function poll(){clearTimeout(pollTimer);jsonFetch('/project-sync/api/deployment-requests/'+encodeURIComponent(current.request.request_id)).then(function(j){renderStatus(j.request);if(!terminal(j.request.status))pollTimer=setTimeout(poll,1200)}).catch(function(e){el('deploy-console').textContent=e.message})}
  function renderStatus(r){var steps=r.steps||[];var lines=steps.map(function(s){return '['+(s.at||'').slice(11,19)+'] '+s.step+' '+s.status});el('deploy-console').textContent=lines.join('\n')||r.status;['backup','apply','refresh','verify'].forEach(function(x){var entries=steps.filter(function(s){return s.step===x});var last=entries[entries.length-1];rail(x,!last?'':last.status==='running'?'active':last.status==='complete'||last.status==='skipped'?'done':'failed')});if(terminal(r.status)){rail('receipt',r.status==='applied'?'done':'failed');var box=el('deploy-receipt-panel');box.classList.remove('d-none');box.innerHTML='';box.appendChild(alertBox(r.status==='applied'?'success':'danger','Deployment '+r.status+(r.error?': '+r.error:'')));var backup=steps.filter(function(s){return s.step==='backup'&&s.receipt}).pop();var verification=steps.filter(function(s){return s.step==='verify'&&s.convergence}).pop();var receipt=document.createElement('pre');receipt.className='scps-console mt-2';receipt.textContent=JSON.stringify({request_id:r.request_id,deployment_id:r.deployment_id||null,commit:r.commit_sha,plan_digest:r.plan_digest,operations:r.operation_summary,backup:backup?backup.receipt:null,convergence:verification?verification.convergence:null},null,2);box.appendChild(receipt);if(r.deployment_id){var a=document.createElement('a');a.className='btn btn-sm btn-outline-primary mt-2';a.href='/project-sync/deployments';a.textContent='Open deployment ledger';box.appendChild(a)}}}
})();
